### ISSUE TITLE
Upload with busboy fails after 2nd chunk or after timeout when using nginx

### ISSUE THREAD

**Issue by bugdanov** [doxel/doxel-loopback#8]
```
Error: expecting chunk 0 got 1
    at Busboy.<anonymous> (/src/doxel-loopback/node_modules/express-plupload/index-busboy.js:59:19)
```

**Comment by bugdanov** [comment]
A little bit better (and more misterious) after setting X-Forwarded-For and disabling cache:
Now it stops uploading on the 4th chunk
```
Error: expecting chunk 1 got 4
    at Busboy.<anonymous> (/home/polto/src/doxel-loopback/node_modules/express-plupload/index-busboy.js:59:19)
```

**Comment by bugdanov** [comment]
The random behaviour comes from fhe 'uploads' global variable used in express-plupload/index-busboy.js that is not shared among processes when running a doxel-loopback cluster in production with strong-pm.

**Comment by bugdanov** [comment]
Also there is a timeout on 'data' events for the stream in the express-plupload module, but nginx receive the full chunk (1Mb) before sending it to the application. When using nginx, it must then be set to the time needed for a very slow upstream internet connection to send 1Mb...

**Comment by bugdanov** [comment]
Now with angular-file-upload we send only one chunk (we dont have to split the upload in chunks until it appears to be needed), so the "cluster" issue is fixed.  The timeout issue is still to be fixed somehow to avoid DOS.

**Comment by bugdanov** [comment]
closing this issue until we switch back to chunked uploads
